### ISSUE TITLE
Visualize robot in rviz

### ISSUE THREAD

**Issue by cmower** [cmower/optas_ros#3]
@mhubii I am wondering if you could lend a hand. I have been unable to work out how to visualize the robot in Rviz, do you have any idea how to add the robot model to the visualization? Please see the launch script [here](https://github.com/cmower/optas_ros/blob/master/optas_ros/launch/linear_differential_ik_controller_example.launch.py). You see that I have the robot description, I am wondering how this is then passed to rviz? Perhaps something needs to generate the joint states like gazebo? In which case, do you know the easiest way to achieve this? 

Any help greatly appreciated.

**Comment by joaomoura24** [comment]
I usually add the robot using the rviz gui and then save the rviz config to file, and then from the launch file you should be able to load the rviz config that you saved using the gui which will have the robot.
Programatically I don't know what is the way.

**Comment by cmower** [comment]
Thanks @joaomoura24. However, the problem is I don't know how to do this in rviz2/ROS2 :wink:

**Comment by mhubii** [comment]
sure, will have a look

**Comment by cmower** [comment]
Thanks @mhubii

The main issue was that in ROS2, the `robot_description` (that needs to be set in Rviz2) is a topic, in ROS1 this was a parameter.
